<template><div><!-- 国密 SM2 SM3 SM4 请求数据加密 使用sm-crypto加密解密-->
<p>前端随机生成 SM2 公钥: publicKey; 私钥: privateKey</p>
<p>调用接口 /getSmBolt 把随机生成的公钥 publicKey 保存在后端，后端返回 SM4 的 bolt，iV 保存在前端; 再调用其他接口 前端使用 sm4.encrypt(data, key, { mode: mode, iv, padding })加密保存数据, 使用 SM3 加密数据生成 Hash 数据 sm3(data)用于验签，后端使用 SM4 和 SM3 解密后数据是否相等，相等则返回 SM4 加密数据，前端用 sm4.decrypt(encrypt, key, { mode: mode, iv, padding })解密</p>
<div class="language-javascript line-numbers-mode" data-ext="js"><pre v-pre class="language-javascript"><code><span class="token comment">// 国密 SM2 SM3 SM4 请求数据加密</span>
<span class="token keyword">const</span> <span class="token punctuation">{</span> sm2<span class="token punctuation">,</span> sm3<span class="token punctuation">,</span> sm4 <span class="token punctuation">}</span> <span class="token operator">=</span> <span class="token function">require</span><span class="token punctuation">(</span><span class="token string">'sm-crypto'</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
<span class="token keyword">const</span> keypair <span class="token operator">=</span> sm2<span class="token punctuation">.</span><span class="token function">generateKeyPairHex</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
<span class="token keyword">const</span> cipherMode <span class="token operator">=</span> <span class="token number">1</span><span class="token punctuation">;</span> <span class="token comment">// 1 - C1C3C2，0 - C1C2C3，默认为1</span>
<span class="token keyword">const</span> padding <span class="token operator">=</span> <span class="token string">'pkcs#5'</span><span class="token punctuation">;</span>
<span class="token keyword">const</span> mode <span class="token operator">=</span> <span class="token string">'cbc'</span><span class="token punctuation">;</span>

<span class="token comment">// 随机生成SM2 公钥 私钥</span>
<span class="token keyword">export</span> <span class="token keyword">const</span> <span class="token function-variable function">getSM2key</span> <span class="token operator">=</span> <span class="token punctuation">(</span><span class="token punctuation">)</span> <span class="token operator">=></span> <span class="token punctuation">{</span>
  <span class="token keyword">return</span> <span class="token punctuation">{</span>
    <span class="token literal-property property">publicKey</span><span class="token operator">:</span> keypair<span class="token punctuation">.</span>publicKey<span class="token punctuation">,</span>
    <span class="token literal-property property">privateKey</span><span class="token operator">:</span> keypair<span class="token punctuation">.</span>privateKey<span class="token punctuation">,</span>
  <span class="token punctuation">}</span><span class="token punctuation">;</span>
<span class="token punctuation">}</span><span class="token punctuation">;</span>

<span class="token comment">// 使用公钥 SM2数据加密</span>
<span class="token keyword">export</span> <span class="token keyword">const</span> <span class="token function-variable function">encryptSM2</span> <span class="token operator">=</span> <span class="token punctuation">(</span><span class="token parameter">data<span class="token punctuation">,</span> publicKey</span><span class="token punctuation">)</span> <span class="token operator">=></span> <span class="token punctuation">{</span>
  <span class="token keyword">return</span> sm2<span class="token punctuation">.</span><span class="token function">doEncrypt</span><span class="token punctuation">(</span>data<span class="token punctuation">,</span> publicKey<span class="token punctuation">,</span> cipherMode<span class="token punctuation">)</span><span class="token punctuation">;</span>
<span class="token punctuation">}</span><span class="token punctuation">;</span>

<span class="token comment">// 使用私钥 SM2数据解密</span>
<span class="token keyword">export</span> <span class="token keyword">const</span> <span class="token function-variable function">decryptSM2</span> <span class="token operator">=</span> <span class="token punctuation">(</span><span class="token parameter">encrypt<span class="token punctuation">,</span> privateKey</span><span class="token punctuation">)</span> <span class="token operator">=></span> <span class="token punctuation">{</span>
  <span class="token keyword">return</span> sm2<span class="token punctuation">.</span><span class="token function">doDecrypt</span><span class="token punctuation">(</span>encrypt<span class="token punctuation">,</span> privateKey<span class="token punctuation">,</span> cipherMode<span class="token punctuation">)</span><span class="token punctuation">;</span>
<span class="token punctuation">}</span><span class="token punctuation">;</span>

<span class="token comment">// 使用SM3加密生成Hash数据</span>
<span class="token keyword">export</span> <span class="token keyword">const</span> <span class="token function-variable function">hashDataSM3</span> <span class="token operator">=</span> <span class="token punctuation">(</span><span class="token parameter">data</span><span class="token punctuation">)</span> <span class="token operator">=></span> <span class="token punctuation">{</span>
  <span class="token keyword">return</span> <span class="token function">sm3</span><span class="token punctuation">(</span>data<span class="token punctuation">)</span><span class="token punctuation">;</span>
<span class="token punctuation">}</span><span class="token punctuation">;</span>

<span class="token comment">// 使用SM4数据加密</span>
<span class="token keyword">export</span> <span class="token keyword">const</span> <span class="token function-variable function">encryptSM4</span> <span class="token operator">=</span> <span class="token punctuation">(</span><span class="token parameter">data<span class="token punctuation">,</span> key<span class="token punctuation">,</span> iv</span><span class="token punctuation">)</span> <span class="token operator">=></span> <span class="token punctuation">{</span>
  <span class="token keyword">return</span> sm4<span class="token punctuation">.</span><span class="token function">encrypt</span><span class="token punctuation">(</span>data<span class="token punctuation">,</span> key<span class="token punctuation">,</span> <span class="token punctuation">{</span> <span class="token literal-property property">mode</span><span class="token operator">:</span> mode<span class="token punctuation">,</span> iv<span class="token punctuation">,</span> padding <span class="token punctuation">}</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
<span class="token punctuation">}</span><span class="token punctuation">;</span>

<span class="token comment">// 使用SM4数据解密</span>
<span class="token keyword">export</span> <span class="token keyword">const</span> <span class="token function-variable function">decryptSM4</span> <span class="token operator">=</span> <span class="token punctuation">(</span><span class="token parameter">encrypt<span class="token punctuation">,</span> key<span class="token punctuation">,</span> iv</span><span class="token punctuation">)</span> <span class="token operator">=></span> <span class="token punctuation">{</span>
  <span class="token keyword">return</span> sm4<span class="token punctuation">.</span><span class="token function">decrypt</span><span class="token punctuation">(</span>encrypt<span class="token punctuation">,</span> key<span class="token punctuation">,</span> <span class="token punctuation">{</span> <span class="token literal-property property">mode</span><span class="token operator">:</span> mode<span class="token punctuation">,</span> iv<span class="token punctuation">,</span> padding <span class="token punctuation">}</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
<span class="token punctuation">}</span><span class="token punctuation">;</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div></div></template>


